//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_IckEtS_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public type()
        {
            this.step = new HashSet<step>();
            this.ticket = new HashSet<ticket>();
        }
    
        public int id { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<step> step { get; set; }
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
